[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s) | size=%(size)s | request=%(request)s | post=%(post)s | response=%(response)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"