SHOW TABLES;

-- IMPORTING THE COSMIAN APP
USE COSMIAN_KMS_ADAMKHAYAM;

-- CREATION OF FUNCTIONS WITH EAI RIGHTS
CALL COSMIAN_KMS_ADAMKHAYAM.CORE.CREATE_EAI_OBJECTS();

-- FOR STORING SECRETS
CREATE SCHEMA IF NOT EXISTS cosmian_integration;
CREATE TABLE IF NOT EXISTS secrets(pk VARCHAR, sk VARCHAR);
--FOR STORING DATA
CREATE SCHEMA IF NOT EXISTS DATA_DEMO;
USE SCHEMA DATA_DEMO;
CREATE TABLE IF NOT EXISTS accounts (ID INT, FIRSTNAME VARCHAR, SURNAME VARCHAR, COMPANY VARCHAR);
TRUNCATE TABLE accounts;
INSERT INTO accounts VALUES
  (1,'A1', 'B1', 'Snowflake'),
  (2,'A2', 'B2', 'Snowflake'),
  (3,'A3', 'B3', 'Snowflake'),
  (4,'A4', 'B4', 'Acme'),
  (5,'A5', 'B5', 'Snowflake'),
  (6,'A6', 'B6', 'Snowflake'),
  (7,'A7', 'B7', 'Snowflake'),
  (8,'A7', 'B8', 'Acme'),
  (9,'A9', 'B9', 'Snowflake'),
  (10,'A10', 'B10', 'Snowflake'),
  (11,'A11', 'B11', 'Snowflake'),
  (12,'A12', 'B12', 'Acme'),
  (13,'A13', 'B13', 'Snowflake'),
  (14,'A14', 'B14', 'Snowflake'),
  (15,'A15', 'B15', 'Snowflake'),
  (16,'A16', 'B16', 'Acme'),
  (17,'A17', 'B17', 'Snowflake'),
  (18,'A18', 'B18', 'Snowflake'),
  (19,'A19', 'B19', 'Snowflake'),
  (20,'A20', 'B20', 'Acme');

INSERT INTO ACCOUNTS
    SELECT 21, COSMIAN_KMS_ADAMKHAYAM.CORE.KMS_ENCRYPT($pk, 'a1'), 'b1', 'c';

SELECT * FROM ACCOUNTS;


-- CREATING KEY PAIRS
Select COSMIAN_KMS_ADAMKHAYAM.CORE.kms_create_keypair(secrets.PK) from secrets;
-- STORING KEYS
INSERT INTO secrets VALUES
 ('d9e549a9-4725-46a7-a41f-128130ad7187','9a6d08e4-da1f-4bf4-9f47-b9ee0636506c');
-- VAR ASSIGNMENT
set pk = 'd9e549a9-4725-46a7-a41f-128130ad7187';
set sk = '9a6d08e4-da1f-4bf4-9f47-b9ee0636506c';


-- TABLE FOR STORING ENCRYPTED VALUES
CREATE TABLE IF NOT EXISTS ENC_NAME_ACCOUNTS (ID INT, FIRSTNAME VARCHAR, SURNAME VARCHAR, COMPANY VARCHAR);
DROP TABLE ENC_NAME_ACCOUNTS;
SELECT * FROM ENC_NAME_ACCOUNTS;


CREATE OR REPLACE FUNCTION encrypt_accounts(PK VARCHAR)
  RETURNS TABLE(ID INT, FIRSTNAME VARIANT, SURNAME VARIANT, COMPANY VARCHAR)
  AS $$
    SELECT ID,
        COSMIAN_KMS_ADAMKHAYAM.CORE.KMS_ENCRYPT(ID, PK, FIRSTNAME) AS FIRSTNAME,
        COSMIAN_KMS_ADAMKHAYAM.CORE.KMS_ENCRYPT(ID, PK, SURNAME) AS SURNAME,
        COMPANY
    FROM ACCOUNTS
  $$;

CREATE OR REPLACE VIEW encrypt_accounts_view
AS (
    SELECT *
    FROM TABLE (ENCRYPT_ACCOUNTS($pk))
    ORDER BY ID);

SELECT * FROM encrypt_accounts_view;

CREATE OR REPLACE PROCEDURE INSERT_ACCOUNT_ENCRYPTION()
RETURNS STRING
LANGUAGE SQL
AS
$$
INSERT INTO ENC_NAME_ACCOUNTS
    (SELECT * FROM ENCRYPT_ACCOUNTS_VIEW);
$$;

CALL INSERT_ACCOUNT_ENCRYPTION();
SELECT * FROM ENC_NAME_ACCOUNTS;



CREATE OR REPLACE FUNCTION decrypt_accounts(SK VARCHAR)
  RETURNS TABLE(ID INT, FIRSTNAME VARIANT, SURNAME VARIANT, COMPANY VARCHAR)
  AS $$
    SELECT ID,
        COSMIAN_KMS_ADAMKHAYAM.CORE.KMS_DECRYPT(ID, SK, FIRSTNAME) AS FIRSTNAME,
        COSMIAN_KMS_ADAMKHAYAM.CORE.KMS_DECRYPT(ID, SK, SURNAME) AS SURNAME,
        COMPANY
    FROM ENC_NAME_ACCOUNTS
    ORDER BY ID
  $$;


CREATE OR REPLACE VIEW decrypted_accounts_view
AS (
    SELECT *
    FROM TABLE (DECRYPT_ACCOUNTS($sk))
    ORDER BY ID);

SELECT * FROM decrypted_accounts_view;






